plot.all.1.0 = function()
{
library(openxlsx)

path = NULL
graph = NULL
firstrawpar = NULL
lastrawpar = NULL
rows = NULL
listraws = NULL
migration.parameter = NULL
param_microsat = NULL
count_microsat = NULL
graph_color = NULL

print('#################################################################################################################################################################################')

print("WELCOME THE R PROGRAM print.all WRITTEN BY PIERO RIVOIRA. THIS IS THE BETA VERSION OF THE SOFTWARE AND IT WORKS ONLY WITH 3 populations, 14 loci, and with parameter 'M'. IF YOU NEED TO RUN print.all WITH MORE COMBINATIONS OF PARAMETERS, FEEL FREE TO E-MAIL ME AT piero.rivoira@yahoo.it. PLEASE DO NOT EDIT THIS FILE UNLESS YOU ARE PERFECTLY AWARE OF WHAT YOU ARE DOING. THE PROGRAM WILL PLOT THE POSTERIOR DENSITIES OF THE MIGRATION PARAMETERS OF ALL THE POSSIBLE PAIRS OF POPULATIONS OR, ALTERNATIVELY, THEIR QUADRATIC APPROXIMATIONS")

print('EVERY TIME YOU NEED TO RE-RUN THE SOFTWARE, PLEASE USE THE FOLLOWING COMMANDS')
print("source('~/popgenetics/R/plot.all')")
print('plot.all()')
print("PLEASE REMEMBER THAT THE DATA FILE MUST BE STORED IN '~/popgenetics/data' AND IT SHOULD BE AN EXCEL FILE (EXTENSION: 'xlsx')")
print(' ---------------------------------------------')
print('YOU WILL BE ASKED TO ENTER AS MANY COLORS AS THERE ARE PARAMETERS')
print(' ---------------------------------------------')

print('#################################################################################################################################################################################')

response = readline(prompt='Please enter "y" if you want to continue or "n" to exit: ')

if (response == 'n')
{
stop('ERROR: YOU CHOSE TO QUIT THE PROGRAM')
}


file_name = readline(prompt='Please enter file name: ')
extension = readline(prompt='Please enter file extension: ')
parameter = readline(prompt='Please enter parameter (gamma (gamma=ΘM) or M (M=m/μ)): ')
graph = readline(prompt='Please enter the graph you would like to plot (PD = Posterior Density or QA = Quadratic Approximation): ')
nloci = as.numeric(readline(prompt='Please enter the number of loci: '))
nbins = as.numeric(readline(prompt='Please enter the number of bins of the posterior distribution: '))
npopulations = as.numeric(readline(prompt='Please enter the number of populations: '))
background = readline(prompt='Please enter background color: ')
foreground = readline(prompt='Please enter foreground color: ')
axis_color = readline(prompt='Please enter axis color: ')
labels_color = readline(prompt='Please enter labels color: ')
first_graph_color = readline(prompt='Please enter first graph color: ')
nparameters = npopulations^2

for(i in 1:(npopulations+2))
{
graph_color[i] = readline(prompt='Please enter graph color: ')
}

if (graph == 'PD')
{
max_y_limit = readline(prompt='Please enter the upper limit of the y axis: ')
max_y_limit = as.numeric(max_y_limit)
}
line_width = readline(prompt='Please enter the line width of the graph: ')
line_width = as.numeric(line_width)

skipraws = nparameters+14
skipraws=skipraws+(nloci*nparameters*(nbins+1))+3*(nbins+1)
firstrawpar4=skipraws+1

lastrawpar4=firstrawpar4+(nbins-1)

rows = as.numeric(c(firstrawpar4:lastrawpar4))
cols = c(5,6)

setwd('~/popgenetics/data')
working_dir = getwd()
path = paste(working_dir, file_name, sep='/')
path = paste(path, '.', extension, sep='')
first.migration.parameter=read.xlsx(xlsxFile=path,sheet = 1,rows=rows,cols=cols,colNames = FALSE)

paramfirst_microsat = first.migration.parameter$X1
countfirst_microsat = first.migration.parameter$X2

par(bg=background, fg = foreground, col.axis = axis_color, col.lab = labels_color)


for(i in 1:(npopulations+2))
{
firstrawpar[i] = firstrawpar4 + (nbins+1)
firstrawpar4 = firstrawpar4 + (nbins+1)
}

lastrawpar = firstrawpar + (nbins-1)

rows5 = as.numeric(c(firstrawpar[1]:lastrawpar[1]))
rows6 = rows5 + (nbins+1)
rows7 = rows6 + (nbins+1)
rows8 = rows7 + (nbins+1)
rows9 = rows8 + (nbins+1)

listraws = list(rows5, rows6, rows7, rows8, rows9)

listmigration.parameter = NULL
listmigration.parameter = read.xlsx(xlsxFile=path,sheet = 1,rows=as.numeric(unlist(listraws[1])),cols=cols,colNames = FALSE)

for(i in 2:(length(listraws)))
{
listmigration.parameter = c(listmigration.parameter, read.xlsx(xlsxFile=path,sheet = 1,rows=as.numeric(unlist(listraws[i])),cols=cols,colNames = FALSE))
} 

param_microsat = as.numeric(unlist(listmigration.parameter[1]))

count_microsat5 = as.numeric(unlist(listmigration.parameter[2]))
count_microsat6 = as.numeric(unlist(listmigration.parameter[4]))
count_microsat7 = as.numeric(unlist(listmigration.parameter[6]))
count_microsat8 = as.numeric(unlist(listmigration.parameter[8]))
count_microsat9 = as.numeric(unlist(listmigration.parameter[10]))

counts_microsat = c(countfirst_microsat, count_microsat5, count_microsat6, count_microsat7, count_microsat8, count_microsat9) 


if (graph == 'QA' & parameter == 'M')
{
log_postprob4 = log(as.numeric(countfirst_microsat))
log_postprob5 = log(as.numeric(count_microsat5))
log_postprob6 = log(as.numeric(count_microsat6))
log_postprob7 = log(as.numeric(count_microsat7))
log_postprob8 = log(as.numeric(count_microsat8))
log_postprob9 = log(as.numeric(count_microsat9))


derivativelogpostprob4 = diff(as.numeric(log_postprob4))/diff(as.numeric(param_microsat))
derivativelogpostprob5 = diff(as.numeric(log_postprob5))/diff(as.numeric(param_microsat))
derivativelogpostprob6 = diff(as.numeric(log_postprob6))/diff(as.numeric(param_microsat))
derivativelogpostprob7 = diff(as.numeric(log_postprob7))/diff(as.numeric(param_microsat))
derivativelogpostprob8 = diff(as.numeric(log_postprob8))/diff(as.numeric(param_microsat))
derivativelogpostprob9 = diff(as.numeric(log_postprob9))/diff(as.numeric(param_microsat))

param_microsat_mod = param_microsat[-1500]
secondderivativelogpostprob4 = diff(derivativelogpostprob4)/diff(as.numeric(param_microsat_mod))
secondderivativelogpostprob5 = diff(derivativelogpostprob5)/diff(as.numeric(param_microsat_mod))
secondderivativelogpostprob6 = diff(derivativelogpostprob6)/diff(as.numeric(param_microsat_mod))
secondderivativelogpostprob7 = diff(derivativelogpostprob7)/diff(as.numeric(param_microsat_mod))
secondderivativelogpostprob8 = diff(derivativelogpostprob8)/diff(as.numeric(param_microsat_mod))
secondderivativelogpostprob9 = diff(derivativelogpostprob9)/diff(as.numeric(param_microsat_mod))

param_microsat_mod_mod = param_microsat_mod[-1499]
mode4 = as.numeric(min(paramfirst_microsat[which(countfirst_microsat == max(countfirst_microsat))]))
mode5 = as.numeric(min(paramfirst_microsat[which(count_microsat5 == max(count_microsat5))]))
mode6 = as.numeric(min(paramfirst_microsat[which(count_microsat6 == max(count_microsat6))]))
mode7 = as.numeric(min(paramfirst_microsat[which(count_microsat7 == max(count_microsat7))]))
mode8 = as.numeric(min(paramfirst_microsat[which(count_microsat8 == max(count_microsat8))]))
mode9 = as.numeric(min(paramfirst_microsat[which(count_microsat9 == max(count_microsat9))]))

quadapp4 = log(as.numeric(max(countfirst_microsat))) + (0.5*(as.numeric(param_microsat_mod_mod)-mode4)^2)*secondderivativelogpostprob4[which(param_microsat_mod_mod == mode4)]
quadapp5 = log(as.numeric(max(count_microsat5))) + (0.5*(as.numeric(param_microsat_mod_mod)-mode5)^2)*secondderivativelogpostprob5[which(param_microsat_mod_mod == mode5)]
quadapp6 = log(as.numeric(max(count_microsat6))) + (0.5*(as.numeric(param_microsat_mod_mod)-mode6)^2)*secondderivativelogpostprob6[which(param_microsat_mod_mod == mode6)]
quadapp7 = log(as.numeric(max(count_microsat7))) + (0.5*(as.numeric(param_microsat_mod_mod)-mode7)^2)*secondderivativelogpostprob7[which(param_microsat_mod_mod == mode7)]
quadapp8 = log(as.numeric(max(count_microsat8))) + (0.5*(as.numeric(param_microsat_mod_mod)-mode8)^2)*secondderivativelogpostprob8[which(param_microsat_mod_mod == mode8)]
quadapp9 = log(as.numeric(max(count_microsat9))) + (0.5*(as.numeric(param_microsat_mod_mod)-mode9)^2)*secondderivativelogpostprob9[which(param_microsat_mod_mod == mode9)]

#quadapps = c(quadapp5, quadapp6, quadapp7, quadapp8, quadapp9)

plot(param_microsat_mod_mod, quadapp4, type='l',lwd=line_width, col=first_graph_color,xlab="M = m/μ",ylab="quadratic approximation of posterior density",cex.lab=2,cex.axis=2)

#for(i in 1:5)
#{
#lines(param_microsat_mod_mod, quadapps[i], type='l',lwd=line_width, col=graph_color[i],xlab="M = m/μ",ylab="quadratic approximation of posterior density",cex.lab=2,cex.axis=2)
#}

lines(param_microsat_mod_mod, quadapp5, type='l',lwd=line_width, col=graph_color[1],xlab="M = m/μ",ylab="quadratic approximation of posterior density",cex.lab=2,cex.axis=2)
lines(param_microsat_mod_mod, quadapp6, type='l',lwd=line_width, col=graph_color[2],xlab="M = m/μ",ylab="quadratic approximation of posterior density",cex.lab=2,cex.axis=2)
lines(param_microsat_mod_mod, quadapp7, type='l',lwd=line_width, col=graph_color[3],xlab="M = m/μ",ylab="quadratic approximation of posterior density",cex.lab=2,cex.axis=2)
lines(param_microsat_mod_mod, quadapp8, type='l',lwd=line_width, col=graph_color[4],xlab="M = m/μ",ylab="quadratic approximation of posterior density",cex.lab=2,cex.axis=2)
lines(param_microsat_mod_mod, quadapp9, type='l',lwd=line_width, col=graph_color[5],xlab="M = m/μ",ylab="quadratic approximation of posterior density",cex.lab=2,cex.axis=2)

legend(0, -200, legend=c('France-CH → Piedmont', 'Valais → Piedmont', 'Piedmont → France-CH', 'Valais → France-CH', 'Piedmont → Valais', 'France-CH → Valais'), col=c('cyan', 'red', 'pink', 'white', 'green', 'blue'), lwd=5, lty=2:3, cex=1)
}

else if (graph == 'QA' & parameter == 'gamma') 
{
plot(param_microsat_mod_mod, quadapp4, type='l',lwd=line_width, col=first_graph_color,xlab='γ=ΘM=xNeμ*m/μ=xNem',ylab="quadratic approximation of posterior density",cex.lab=2,cex.axis=2)
}



if (graph == 'PD' & parameter == 'M')
{
plot(paramfirst_microsat,countfirst_microsat,type='l',lwd=line_width,col=first_graph_color,xlab='M = m/μ',ylab='posterior density',cex.lab=2,cex.axis=2,ylim=c(0,max_y_limit))
}
else if (graph == 'PD' & parameter == 'gamma')
{
plot(paramfirst_microsat,countfirst_microsat,type='l',lwd=line_width,col=first_graph_color,xlab='γ=ΘM=xNeμ*m/μ=xNem',ylab='posterior density',cex.lab=2,cex.axis=2,ylim=c(0,max_y_limit))
}

if (graph == 'PD' & parameter == 'M' | parameter == 'gamma')
{
lines(param_microsat,count_microsat5,type='l',lwd=line_width,col=(graph_color[1]),xlab='M = m/μ',ylab='posterior density',cex.lab=2,cex.axis=2,ylim=c(0,max_y_limit))
lines(param_microsat,count_microsat6,type='l',lwd=line_width,col=(graph_color[2]),xlab='M = m/μ',ylab='posterior density',cex.lab=2,cex.axis=2,ylim=c(0,max_y_limit))
lines(param_microsat,count_microsat7,type='l',lwd=line_width,col=(graph_color[3]),xlab='M = m/μ',ylab='posterior density',cex.lab=2,cex.axis=2,ylim=c(0,max_y_limit))
lines(param_microsat,count_microsat8,type='l',lwd=line_width,col=(graph_color[4]),xlab='M = m/μ',ylab='posterior density',cex.lab=2,cex.axis=2,ylim=c(0,max_y_limit))
lines(param_microsat,count_microsat9,type='l',lwd=line_width,col=(graph_color[5]),xlab='M = m/μ',ylab='posterior density',cex.lab=2,cex.axis=2,ylim=c(0,max_y_limit))

legend(600, 0.02, legend=c('France-CH → Piedmont', 'Valais → Piedmont', 'Piedmont → France-CH', 'Valais → France-CH', 'Piedmont → Valais', 'France-CH → Valais'), col=c('cyan', 'red', 'pink', 'white', 'green', 'blue'), lwd=5, lty=2:3, cex=1)
}

mode4 = paramfirst_microsat[which(countfirst_microsat == max(countfirst_microsat))]
mode5 = param_microsat[which(count_microsat5 == max(count_microsat5))]
mode6 = param_microsat[which(count_microsat6 == max(count_microsat6))]
mode7 = param_microsat[which(count_microsat7 == max(count_microsat7))]
mode8 = param_microsat[which(count_microsat8 == max(count_microsat8))]
mode9 = param_microsat[which(count_microsat9 == max(count_microsat9))]

modes = c(mode4, mode5, mode6, mode7, mode8, mode9)

#result = str(first.migration.parameter)

#return(parameter)
#return(result)
return(modes)

#print(paste('The kind of the first migration parameter is', parameter))
#print(paste('The structure of the first migration parameter is', result))
print(paste('The modes of the distribution are', modes))


if (graph == 'PD' & parameter == 'M' | graph == 'PD' & parameter == 'gamma' | graph == 'QA' & parameter == 'M' | graph == 'QA' & parameter == 'gamma')
{
print('Parameters entered correctly')
}
else
{
print('Error')
}
}
